#!/usr/bin/env sh

# Created by: Vladislav Punko <iam.vlad.punko@gmail.com>
# Created date: 2023-06-25

set -o errexit
set -o nounset

brew update

# Upgrade all homebrew-installed packages to their latest versions.
brew upgrade
brew upgrade --cask

# Remove all contents from the homebrew cache directory.
rm -f -r -- "$(brew --cache)"

# Refresh the primary virus definitions on this system.
freshclam --show-progress

# Update all programs and packages of the main scientific computation system.
"${HOME}/.miniconda/bin/conda" update --yes --update-all
