---
- include_vars: vars/system_packages.yml

- name: install system dependencies and updates
  block:
    - name: install the required applications on the current machine
      environment:
        HOMEBREW_NO_AUTO_UPDATE: 1
      homebrew_cask:
        install_options: force # necessary for casks that overwrite existing apps or have pre-installed components
        name: "{{ required_homebrew_casks }}"
        state: latest

    - name: install essential system packages and development tools
      environment:
        HOMEBREW_NO_AUTO_UPDATE: 1
      homebrew:
        name: "{{ required_homebrew_packages }}"
        state: latest
  always:
    - name: remove all contents from the homebrew cache directory
      environment:
        # It is assumed that the session from which playbook is launched does not contain a configured path to search for homebrew.
        PATH: "/opt/homebrew/bin:{{ lookup('ansible.builtin.env', 'PATH') }}"
      command: rm -f -r -- "$(brew --cache)"
  when: ansible_distribution == "MacOSX"
  tags:
    - packages
    - packages-workstation
