---
- include_vars: vars/dotfiles.yml
- include_vars: vars/vscode_extensions.yml

- name: set user's settings for programs and packages
  block:
    - name: Update user's shell
      become: true
      become_method: sudo
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh

    - name: create new directories to store user's settings on the current machine
      file:
        path: "{{ item.dest | dirname }}" # get the absolute path to store this file on the current machine
        state: directory
        recurse: false
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
      with_items: "{{ dotfiles }}"

    - name: set user's settings for the required programs and packages on the current operating system
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0600
      with_items: "{{ dotfiles }}"

    - name: set user's settings for the main graphical user interface on the current operating system
      shell: dconf load / < files/views/gnome_views.settings # restore the main desktop settings
      args:
        chdir: "{{ playbook_dir }}" # change the current working directory before running this command
  always:
    - name: reload all user's services on the current machine
      systemd:
        daemon_reload: true
        scope: user
  when: ansible_distribution == "Fedora"
  tags:
    - dotfiles
    - dotfiles-workstation

- name: provision visual studio code environment
  block:
    - name: install the requred visual studio code extensions on the current machine
      command: code --force --install-extension "{{ item }}"
      with_items: "{{ required_vscode_extensions }}"
  when: ansible_distribution == "Fedora"
  tags:
    - vscode
    - vscode-workstation

- name: linux post-installation steps for the docker engine
  become: true
  become_method: sudo
  block:
    - name: create the docker group on the current machine
      group:
        name: docker # new group in order to run docker as a non-root user
        state: present

    - name: add the current user to the docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: true
  when: ansible_distribution == "Fedora"
  tags:
    - docker
    - docker-workstation

- name: grant flameshot screenshot permission
  block:
    - name: set the required screenshot permission for flameshot
      command: >
        dbus-send --session --print-reply=literal --dest=org.freedesktop.impl.portal.PermissionStore /org/freedesktop/impl/portal/PermissionStore org.freedesktop.impl.portal.PermissionStore.SetPermission string:'screenshot' boolean:true string:'screenshot' string:'org.flameshot.Flameshot' array:string:'yes'

    - name: check screenshot permission
      command: >
        dbus-send --session --print-reply=literal --dest=org.freedesktop.impl.portal.PermissionStore /org/freedesktop/impl/portal/PermissionStore org.freedesktop.impl.portal.PermissionStore.Lookup string:'screenshot' string:'screenshot'
      register: screenshot_permission_check

    - debug:
        var: screenshot_permission_check.stdout
  when: ansible_distribution == "Fedora"
  tags:
    - screenshot-permissions
    - screenshot-permissions-workstation
