---
- include_vars: vars/dotfiles.yml
- include_vars: vars/vscode_extensions.yml

- name: set user's settings for programs and packages
  block:
    - name: create new directories to store user's settings on the current machine
      file:
        path: "{{ item.dest | dirname }}" # get the absolute path to store this file on the current machine
        state: directory
        recurse: false
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0755
      with_items: "{{ dotfiles }}"

    - name: set user's settings for the required programs and packages on the current operating system
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0600
      with_items: "{{ dotfiles }}"
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
    - dotfiles-workstation

- name: provision visual studio code environment
  block:
    - name: install the requred visual studio code extensions on the current machine
      environment:
        # It is assumed that the working shell session from which this playbook was launched is not yet configured.
        PATH: "/opt/homebrew/bin:{{ lookup('ansible.builtin.env', 'PATH') }}"
      command: code --force --install-extension "{{ item }}"
      with_items: "{{ required_vscode_extensions }}"
  when: ansible_distribution == "MacOSX"
  tags:
    - vscode
    - vscode-workstation
