---
required_vscode_extensions:
  - docker.docker
  - ms-azuretools.vscode-containers
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.remote-explorer
  - visualstudioexptteam.vscodeintellicode # ai-assisted development features for python
